let nome = prompt ("Digite o seu nome")
let variavel = prompt ("Digite um número")
let variavel2 = prompt ("Digite um outro número")
const soma = parseInt (variavel) + parseInt (variavel2)
const subtracao = parseInt (variavel) - parseInt(variavel2)
const multiplicacao = parseInt (variavel) * parseInt (variavel2)
const divisao = parseInt (variavel) / parseInt (variavel2)

alert ("A soma dos valores equivale a " + soma)
alert ("A subtração dos valores equivale a " + subtracao)
alert ("A multiplicação dos valores equivale a " + multiplicacao)
alert ("A divisão dos valores equivale a " + divisao)